config/routes.rb
Rails.application.routes.draw do
  resources :cardigans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cardigans#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cardigan.rb
class Cardigan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cardigans_controller.rb
class CardigansController < ApplicationController
  before_action :set_cardigan, only: [:show, :edit, :update, :destroy]

  # GET /cardigans
  # GET /cardigans.json
  def index
    @cardigans = Cardigan.all
  end

  # GET /cardigans/1
  # GET /cardigans/1.json
  def show
  end

  # GET /cardigans/new
  def new
    @cardigan = Cardigan.new
  end

  # GET /cardigans/1/edit
  def edit
  end

  # POST /cardigans
  # POST /cardigans.json
  def create
    @cardigan = Cardigan.new(cardigan_params)

    respond_to do |format|
      if @cardigan.save
        format.html { redirect_to @cardigan, notice: 'Cardigan was successfully created.' }
        format.json { render :show, status: :created, location: @cardigan }
      else
        format.html { render :new }
        format.json { render json: @cardigan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cardigans/1
  # PATCH/PUT /cardigans/1.json
  def update
    respond_to do |format|
      if @cardigan.update(cardigan_params)
        format.html { redirect_to @cardigan, notice: 'Cardigan was successfully updated.' }
        format.json { render :show, status: :ok, location: @cardigan }
      else
        format.html { render :edit }
        format.json { render json: @cardigan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cardigans/1
  # DELETE /cardigans/1.json
  def destroy
    @cardigan.destroy
    respond_to do |format|
      format.html { redirect_to cardigans_url, notice: 'Cardigan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cardigan
      @cardigan = Cardigan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cardigan_params
      params.require(:cardigan).permit(:brand, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cardigans_helper.rb
module CardigansHelper
end

app/views/cardigans/_form.html.erb
<%= form_for(cardigan) do |f| %>
  <% if cardigan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cardigan.errors.count, "error") %> prohibited this cardigan from being saved:</h2>

      <ul>
      <% cardigan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cardigans/edit.html.erb
<h1>Editing Cardigan</h1>

<%= render 'form', cardigan: @cardigan %>

<%= link_to 'Show', @cardigan %> |
<%= link_to 'Back', cardigans_path %>

app/views/cardigans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cardigans</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cardigans.each do |cardigan| %>
      <tr>
        <td><%= cardigan.brand %></td>
        <td><%= cardigan.color %></td>
        <td><%= link_to 'Show', cardigan %></td>
        <td><%= link_to 'Edit', edit_cardigan_path(cardigan) %></td>
        <td><%= link_to 'Destroy', cardigan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cardigan', new_cardigan_path %>

app/views/cardigans/new.html.erb
<h1>New Cardigan</h1>

<%= render 'form', cardigan: @cardigan %>

<%= link_to 'Back', cardigans_path %>

app/views/cardigans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @cardigan.brand %>
</p>

<p>
  <strong>Color:</strong>
  <%= @cardigan.color %>
</p>

<%= link_to 'Edit', edit_cardigan_path(@cardigan) %> |
<%= link_to 'Back', cardigans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CardiganTrack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>